<?php
/**
 * Rokezzz_Bakery
 *
 * @category    Rokezzz
 * @package     Rokezzz_Bakery
 * @author      Michał Kaszak <michalosmpk@gmail.com>
 * @copyright   Copyright (c) 2024 Michał Kaszak
 */

?>
<section class="About ContentWrapper">
    <div class="About__Grid">
        <div class="About__GridLeft">
            <h2 class="About__Title">About Our Bakery</h2>
            <div class="About__Text">
                At Rokezzz, we are passionate about crafting delightful baked goods that not only tantalize your taste buds but also warm your heart. With a legacy of 22 years in the baking industry, we have honed our skills to perfection, bringing you the finest treats made with love and expertise.
            </div>
            <div class="About__Text">
                Become a part of the Rokezzz family and embark on a journey of flavor, tradition, and happiness. Follow us on social media, subscribe to our newsletter, or visit our website to stay updated on the latest offerings, promotions, and events. We look forward to sharing our passion for baking with you!
            </div>
        </div>
        <div class="About__GridRight">
            <div class="About__Image">
                <img class="About__ImageBottom" src="https://hips.hearstapps.com/hmg-prod/images/types-of-bread-1666723473.jpg?crop=0.663xw:1.00xh;0.169xw,0&resize=640:*" />
                <img class="About__ImageTop" src="https://serenalissy.com/wp-content/uploads/2021/09/cropped-Bread-Baking-Tips-for-Beginners.jpg" />
            </div>
        </div>
    </div>
</section>