<?php
/**
 * Rokezzz_Bakery
 *
 * @category    Rokezzz
 * @package     Rokezzz_Bakery
 * @author      Michał Kaszak <michalosmpk@gmail.com>
 * @copyright   Copyright (c) 2024 Michał Kaszak
 */

?>
<section class="Contact ContentWrapper">
    <div class="Contact__Grid">
        <form class="Contact__Form">
            <div class="Contact__FormRow">
                <div class="Contact__FormCell Contact__FormName">
                    <p>Name</p>
                    <input type="text" name="name" required="true" placeholder="Name" />
                </div>
                <div class="Contact__FormCell Contact__FormSurname">
                    <p>Surname</p>
                    <input type="text" name="surname" required="true" placeholder="Surname" />
                </div>
            </div>
            <div class="Contact__FormRow">
                <div class="Contact__FormCell Contact__FormPhone">
                    <p>Phone Number</p>
                    <input type="tel" name="phone" required="false" placeholder="" />
                </div>
            </div>
            <div class="Contact__FormRow">
                <div class="Contact__FormCell Contact__FormEmail">
                    <p>Email</p>
                    <input type="email" name="email" required="true" placeholder="Email" />
                </div>
            </div>
            <div class="Contact__FormRow">
                <div class="Contact__FormCell Contact__FormMessage">
                    <p>Message</p>
                    <textarea name="message" placeholder="Type your message here..." required></textarea>
                </div>
            </div>
            <div class="Contact__FormRow">
                <button type="submit">
                    Submit
                </button>
            </div>
        </form>
        <div class="Contact__GridRight">
            <h2 class="Contact__Title">Get in Touch with Us!</h2>
            <p class="Contact__Text">
                Have a question or feedback? We'd love to hear from you! Feel free to reach out using the contact form below. Whether you're inquiring about our delicious pastries, placing a custom order for your special event, or simply want to say hello, we're here to help. Our team at Rokezzz is dedicated to providing you with the best bakery experience possible. Fill out the form, and we'll get back to you as soon as possible.
            </p>
        </div>
    </div>
</section>